#!/bin/sh
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${HDF5_ROOT} \
        -DHDF5_ENABLE_PARALLEL:BOOL=ON -DHDF5_ENABLE_THREADSAFE:BOOL=ON \
        -DALLOW_UNSUPPORTED:BOOL=ON ..
make all install -j8